import { createClient } from "@supabase/supabase-js";
import * as dotenv from "dotenv";
dotenv.config({ path: ".env.local" });

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!
);

const AOS = [
  { titre: "Travaux de chaudronnerie — Station de traitement des eaux Bordeaux", secteur: "Chaudronnerie", score_ia: 9, description_courte: "Fabrication et installation de cuves acier inoxydable 316L", source_url: "https://www.boamp.fr/avis/detail/24-1001", resume_ia: "Marché de chaudronnerie industrielle pour la STEP de Bordeaux. Fort alignement avec le profil Chaudronnerie. Budget estimé 340k€, délai réponse 6 semaines.", draft_email: "Madame, Monsieur,\n\nNous avons pris connaissance de votre appel d'offres n°24-1001 relatif à des travaux de chaudronnerie pour votre station de traitement des eaux.\n\nFort de 15 ans d'expérience dans la fabrication de cuves et équipements en acier inoxydable, notre entreprise présente toutes les garanties techniques et financières pour répondre à vos besoins.\n\nNous vous prions d'agréer, Madame, Monsieur, l'expression de nos salutations distinguées.", date_limite: "2026-05-15" },
  { titre: "Maintenance soudure réservoirs GPL — Distribution Île-de-France", secteur: "Soudure", score_ia: 8, description_courte: "Intervention soudure TIG sur réservoirs sous pression classe 1", source_url: "https://www.boamp.fr/avis/detail/24-1002", resume_ia: "Contrat cadre maintenance soudure sur 2 ans, réservoirs GPL. Exige qualification ASME ou équivalent. Très bonne correspondance profil soudure TIG.", draft_email: "Madame, Monsieur,\n\nSuite à la publication de votre avis relatif à la maintenance soudure de vos réservoirs GPL en Île-de-France, nous souhaitons vous présenter notre candidature.\n\nNotre équipe est qualifiée TIG/MIG et dispose des certifications requises pour les travaux sous pression.\n\nCordialement,", date_limite: "2026-05-20" },
  { titre: "Installation réseau plomberie — Lycée Jean Moulin Lyon", secteur: "Plomberie", score_ia: 7, description_courte: "Rénovation complète réseau eau chaude/froide, 3 500 m²", source_url: "https://www.boamp.fr/avis/detail/24-1003", resume_ia: "Rénovation plomberie lycée public, montant estimé 180k€. Délai chantier 8 semaines en période estivale. Bon potentiel.", draft_email: "Madame, Monsieur,\n\nEn réponse à votre consultation pour la rénovation du réseau plomberie du lycée Jean Moulin, nous vous adressons notre dossier de candidature.\n\nSpécialisés dans les chantiers de rénovation en milieu scolaire, nous intervenons régulièrement sur ce type de marchés.\n\nBien cordialement,", date_limite: "2026-05-25" },
  { titre: "Mise aux normes électrique — Mairie de Strasbourg", secteur: "Électricité", score_ia: 6, description_courte: "Mise en conformité tableau électrique bâtiment administratif", source_url: "https://www.boamp.fr/avis/detail/24-1004", resume_ia: "Marché de mise aux normes, montant modeste (45k€) mais récurrent et renouvelable. Score moyen car hors spécialité principale.", draft_email: "Madame, Monsieur,\n\nNous candidatons à votre marché de mise aux normes électrique.\n\nNotre entreprise est certifiée RGE et Qualifelec. Nous disposons de toutes les habilitations requises pour ce type d'intervention.\n\nCordialement,", date_limite: "2026-06-01" },
  { titre: "Fabrication passerelles acier — Port autonome de Marseille", secteur: "Chaudronnerie", score_ia: 9, description_courte: "Conception et fabrication de 6 passerelles industrielles galvanisées 12m", source_url: "https://www.boamp.fr/avis/detail/24-1005", resume_ia: "Grand marché chaudronnerie structurelle, montant 680k€. Fort alignement profil. Exige certification EN 1090-2. Délai de réponse 8 semaines.", draft_email: "Madame, Monsieur,\n\nNous candidatons avec enthousiasme à votre appel d'offres pour la fabrication de passerelles industrielles au Port de Marseille.\n\nNotre bureau d'études et notre atelier de production sont certifiés EN 1090-2 pour les structures métalliques de classe EXC2.\n\nBien à vous,", date_limite: "2026-06-10" },
  { titre: "Menuiserie intérieure — Centre hospitalier de Toulouse", secteur: "Menuiserie", score_ia: 5, description_courte: "Fourniture et pose de 280 portes coupe-feu EI60", source_url: "https://www.boamp.fr/avis/detail/24-1006", resume_ia: "Marché menuiserie hôpital, contraintes techniques élevées (EI60, accessibilité PMR). Montant 95k€.", draft_email: "Madame, Monsieur,\n\nNous vous présentons notre candidature pour la fourniture et pose de portes coupe-feu EI60.\n\nNous avons réalisé des chantiers similaires dans plusieurs établissements de santé de la région.\n\nCordialement,", date_limite: "2026-06-15" },
  { titre: "Travaux maçonnerie — Extension école primaire Nantes", secteur: "Maçonnerie", score_ia: 4, description_courte: "Extension bâtiment scolaire, gros oeuvre 450 m²", source_url: "https://www.boamp.fr/avis/detail/24-1007", resume_ia: "Marché gros oeuvre extension école, montant estimé 320k€. Score moyen car éloigné de la spécialité principale.", draft_email: "Madame, Monsieur,\n\nNous vous adressons notre dossier de candidature pour le marché d'extension de votre école primaire.\n\nNotre entreprise réalise régulièrement des chantiers de construction et d'extension en milieu scolaire.\n\nBien cordialement,", date_limite: "2026-06-20" },
  { titre: "Tuyauterie industrielle — Raffinerie TotalEnergies Normandie", secteur: "Tuyauterie", score_ia: 9, description_courte: "Remplacement tuyauteries haute pression DN300, PN40", source_url: "https://www.boamp.fr/avis/detail/24-1008", resume_ia: "Marché exceptionnel tuyauterie pétrochimique, montant 1,2M€. Profil idéal. Exige qualification CEFRI et aptitude médicale. Durée chantier 3 semaines en arrêt programmé.", draft_email: "Madame, Monsieur,\n\nNous répondons à votre avis de marché pour le remplacement des tuyauteries haute pression DN300.\n\nNotre équipe dispose des qualifications CEFRI et de toutes les aptitudes requises pour les interventions en milieu pétrochimique.\n\nBien à vous,", date_limite: "2026-07-01" },
  { titre: "Soudure charpente métallique — Hangar logistique Roissy", secteur: "Soudure", score_ia: 7, description_courte: "Assemblage et soudure structure acier 2 400 m², MAG process", source_url: "https://www.boamp.fr/avis/detail/24-1009", resume_ia: "Grand hangar logistique aéroportuaire. Soudure MAG structure primaire et secondaire. Délai 12 semaines, montant 480k€.", draft_email: "Madame, Monsieur,\n\nSuite à la publication de votre consultation, nous vous soumettons notre candidature pour les travaux de soudure de charpente métallique.\n\nNotre atelier mobile intervient sur les grands chantiers de charpente et dispose de l'ensemble des certifications soudage requises.\n\nCordialement,", date_limite: "2026-07-10" },
  { titre: "Réseau eau potable — Extension réseau AEP Clermont-Ferrand", secteur: "Plomberie", score_ia: 6, description_courte: "Extension réseau AEP, pose 3,2 km canalisations fonte DN150", source_url: "https://www.boamp.fr/avis/detail/24-1010", resume_ia: "Marché réseau eau potable communal, montant 620k€. Compétences TP et plomberie requises. Bon potentiel pour profil mixte.", draft_email: "Madame, Monsieur,\n\nNous vous soumettons notre offre pour l'extension du réseau AEP sur votre commune.\n\nFort de notre expérience dans les réseaux humides et la pose de canalisations, nous sommes en mesure de répondre à l'ensemble des exigences techniques de ce marché.\n\nBien cordialement,", date_limite: "2026-07-15" },
];

async function seed() {
  console.log("🌱 Seeding OFFRIO database...\n");

  for (const ao of AOS) {
    const { error } = await supabase.from("appels_offres").insert(ao);
    if (error) {
      console.error(`✗ Error inserting: ${ao.titre.slice(0, 50)} — ${error.message}`);
    } else {
      console.log(`✓ ${ao.titre.slice(0, 60)}`);
    }
  }

  console.log("\n✅ Seed complete! 10 AOs inserted.");
  console.log("\nℹ️  To assign AOs to a user, use the n8n API:");
  console.log("   POST /api/data/aos with { ...ao, client_email: 'user@example.com' }");
}

seed().catch(console.error);
